#SwagLabs URL
SwagURL=https://www.saucedemo.com/

#UserName Locater
UserName_Locater=user-name

#Password Locater
Password_Locater=password

#Login Button Locater
LoginButton_Locater=//input[@value="Login"] 